platform :ios, '14.0'

target 'TMDBSample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TMDBSample
  pod 'Texture', '~> 3.1'
  pod 'PromiseKit', '~> 6.15'
  
  target 'TMDBSampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TMDBSampleUITests' do
    # Pods for testing
  end

end
