platform :ios, '14.0'
inhibit_all_warnings!

target 'TMDBSample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TMDBSample
  pod 'Texture', '~> 3.1'
  pod 'PromiseKit', '~> 6.15'
  pod 'Swinject', '~> 2.7.1'
  
  target 'TMDBSampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TMDBSampleUITests' do
    # Pods for testing
  end

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
    end
  end
end
